ALTER TABLE settings
  DROP PRIMARY KEY,
  MODIFY id INT AUTO_INCREMENT PRIMARY KEY,
  ADD COLUMN user_id INT UNIQUE,
  ADD CONSTRAINT fk_settings_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
